window.weekWords = window.weekWords || {}
window.weekWords.Week1 = [
    { word: "start", definition: "v./n. 开始" },
    { word: "keep", definition: "v. 保持，坚持" },
    { word: "food", definition: "n. 食物" },
    { word: "eat", definition: "v. 吃" },
    { word: "tail", definition: "n. 尾巴" },
    { word: "wrong", definition: "adj. 错的" },
    { word: "nose", definition: "n. 鼻子" },
    { word: "rose", definition: "n. 玫瑰（花）" },
    { word: "hate", definition: "v. 仇恨" },
    { word: "ear", definition: "n. 耳朵" },
    { word: "silk", definition: "n. 丝绸" },
    { word: "ant", definition: "n. 蚂蚁" },
    { word: "bit", definition: "n. 一点" },
    { word: "friend", definition: "n. 朋友" },
    { word: "deaf", definition: "adj. 聋的" },
    { word: "bet", definition: "v. 打赌" },
    { word: "disk", definition: "n. 磁盘" },
    { word: "bird", definition: "n. 鸟" },
    { word: "nut", definition: "n. 坚果" },
    { word: "clock", definition: "n. 钟" },
    { word: "blog", definition: "n. 博客" },
    { word: "king", definition: "n. 国王" },
    { word: "bean", definition: "n. 豆" },
    { word: "bless", definition: "v. 祝福" },
    { word: "give", definition: "v. 给予" },
    { word: "blood", definition: "n. 血" },
    { word: "drink", definition: "v. 喝" },
    { word: "door", definition: "n. 门" },
    { word: "church", definition: "n. 教堂" },
    { word: "blouse", definition: "n. 衬衫" },
    { word: "card", definition: "n. 卡片"},
    { word: "ask", definition: "v. 问，要求"},
    { word: "hope", definition: "v./n. 希望"},
    { word: "kick", definition: "n./v. 踢"},
    { word: "bark", definition: "v. 狗吠"},
    { word: "fruit", definition: "n. 水果"},
    { word: "town", definition: "n. 城镇"},
    { word: "beard", definition: "n. 胡须"},
    { word: "lung", definition: "n. 肺"},
    { word: "earth", definition: "n. 地球"},
    { word: "feed", definition: "v. 喂养"},
    { word: "beef", definition: "n. 牛肉"},
    { word: "fact", definition: "n. 事实"},
    { word: "coat", definition: "n. 外套"},
    { word: "coal", definition: "n. 煤"},
    { word: "climb", definition: "v. 攀登"},
    { word: "boat", definition: "n. 船"},
    { word: "bone", definition: "n. 骨头"},
    { word: "know", definition: "v. 知道"},
    { word: "laugh", definition: "v./n. 笑"},
    { word: "juice", definition: "n. 果汁"},
    { word: "boss", definition: "n. 老板"},
    { word: "wash", definition: "v. 洗"},
    { word: "spy", definition: "n. 间谍"},
    { word: "web", definition: "n. 网"},
    { word: "ton", definition: "n. 吨"},
    { word: "tray", definition: "n. 托盘"},
    { word: "toy", definition: "n. 玩具"},
    { word: "weird", definition: "adj. 奇怪的"},
    { word: "week", definition: "n. 星期，周"},
    { word: "truck", definition: "n. 卡车"},
    { word: "thief", definition: "n. 小偷"},
    { word: "doubt", definition: "n./v. 怀疑"},
    { word: "chat", definition: "v./n. 聊天"},
    { word: "large", definition: "adj. 大的"},
    { word: "noise", definition: "n. 噪音"},
    { word: "pond", definition: "n. 池塘"},
    { word: "boot", definition: "n. 靴子"},
    { word: "fun", definition: "n. 乐趣"},
    { word: "search", definition: "v./n. 搜素"},
    { word: "guess", definition: "v./n. 猜测"},
    { word: "bleed", definition: "v. 流血，出血"},
    { word: "fry", definition: "v. 油炸"},
    { word: "beer", definition: "n. 啤酒"},
    { word: "joke", definition: "n./v. 笑话，玩笑"},
    { word: "jump", definition: "n./v. 跳跃"},
    { word: "debt", definition: "n. 债，债务"},
    { word: "guest", definition: "n. 客人"},
    { word: "gun", definition: "n. 枪"},
    { word: "shut", definition: "v. 关上，关闭"},
    { word: "scarf", definition: "n. 围巾"},
    { word: "gene", definition: "n. 基因"},
    { word: "shelf", definition: "n. 架子"},
    { word: "throat", definition: "n. 咽喉，嗓子"},
    { word: "jazz", definition: "n. 爵士乐"},
    { word: "map", definition: "n. 地图"},
    { word: "plan", definition: "n./v. 计划"},
    { word: "joint", definition: "adj. 联合的"},
    { word: "wool", definition: "n. 羊毛"},
    { word: "sweat", definition: "n. 汗"},
    { word: "milk", definition: "n. 牛奶"},
    { word: "cheap", definition: "adj. 便宜的"},
    { word: "lawn", definition: "n. 草坪，草地"},
    { word: "both", definition: "adj./pron. 两者都"},
    { word: "jeans", definition: "n. 牛仔裤"},
    { word: "leg", definition: "n. 腿"},
    { word: "jog", definition: "v./n. 慢跑"},
    { word: "mud", definition: "n. 泥浆"},
    { word: "mug", definition: "n. 杯子"},
    { word: "sell", definition: "v. 卖，出售"},
    { word: "mile", definition: "n. 英里"},
    { word: "neck", definition: "n. 脖子"},
    { word: "rain", definition: "n./v. 雨，下雨"},
    { word: "sand", definition: "n. 沙子"},
    { word: "pork", definition: "n. 猪肉"},
    { word: "rat", definition: "n. 老鼠"},
    { word: "sock", definition: "n. 短袜"},
    { word: "cloud", definition: "n. 云"},
    { word: "whale", definition: "n. 鲸鱼"},
    { word: "cute", definition: "adj. 可爱的"},
    { word: "neat", definition: "adj. 整洁的"},
    { word: "cold", definition: "adj. 冷的"},
    { word: "grab", definition: "v. 抓住"},
    { word: "goods", definition: "n. 商品"},
    { word: "clown", definition: "n. 小丑"},
    { word: "steak", definition: "n. 牛排"},
    { word: "corn", definition: "n. 玉米"},
    { word: "nice", definition: "adj. 美好的"},
    { word: "god", definition: "n. 神"},
    { word: "night", definition: "n. 夜晚"},
    { word: "wise", definition: "adj. 明智的"},
    { word: "speech", definition: "n. 演讲"},
    { word: "phrase", definition: "n. 短语"},
    { word: "roast", definition: "v. 烤，烘"},
    { word: "pea", definition: "n. 豌豆"},
    { word: "pear", definition: "n. 梨"},
    { word: "help", definition: "v./n. 帮助"},
    { word: "shore", definition: "n. 海滨，湖滨"},
    { word: "ward", definition: "n. 病房"},
    { word: "spoon", definition: "n. 勺子"},
    { word: "hill", definition: "n. 小山"},
    { word: "wine", definition: "n. 葡萄酒"},
    { word: "rub", definition: "v. 擦，摩擦"},
    { word: "herb", definition: "n. 草本植物"},
    { word: "dare", definition: "v. 敢，胆敢"},
    { word: "bunch", definition: "n. 簇，束，捆，串"},
    { word: "shoe", definition: "n. 鞋子"},
    { word: "pie", definition: "n. 馅饼"},
    { word: "steal", definition: "v. 窃取"},
    { word: "wife", definition: "n. 妻子"},
    { word: "hen", definition: "n. 母鸡"},
    { word: "wood", definition: "n. 木材"},
    { word: "crash", definition: "v./n. 碰撞"},
    { word: "here", definition: "adv. 在这里"},
    { word: "dream", definition: "n./v. 梦，做梦"},
    { word: "zone", definition: "n. 地区，区域"},
    { word: "sow", definition: "v. 播种"},
    { word: "rope", definition: "n. 绳"},
    { word: "thing", definition: "n. 事情，东西"},
    { word: "waist", definition: "n. 腰"},
    { word: "pale", definition: "adj. 苍白的；浅的"},
    { word: "cage", definition: "n. 鸟笼"},
    { word: "lid", definition: "n. 盖子"},
    { word: "late", definition: "adj./adv. 晚的(地)，迟的(地)"},
    { word: "pot", definition: "n. 锅"},
    { word: "pound", definition: "n. 镑，英镑"},
    { word: "ache", definition: "v./n. 疼痛"},
    { word: "lamp", definition: "n. 灯"},
    { word: "pipe", definition: "n. 管子"}
],
window.weekWords.Week2 = [
    { word: "skin", definition: "n. 皮肤"},
    { word: "sky", definition: "n. 天空"},
    { word: "scream", definition: "n./v. 尖叫"},
    { word: "salt", definition: "n. 食盐"},
    { word: "same", definition: "adj. 相同的"},
    { word: "vase", definition: "n. 花瓶"},
    { word: "cheek", definition: "n. 脸颊"},
    { word: "pill", definition: "n. 药丸"},
    { word: "brush", definition: "n. 刷子"},
    { word: "zoo", definition: "n. 动物园"},
    { word: "sew", definition: "v. 缝，缝补"},
    { word: "chest", definition: "n. 胸部"},
    { word: "port", definition: "n. 港口"},
    { word: "purse", definition: "n. 钱包"},
    { word: "burn", definition: "v. 燃烧"},
    { word: "year", definition: "n. 年"},
    { word: "bride", definition: "n. 新娘"},
    { word: "flash", definition: "v./n. 闪光"},
    { word: "shark", definition: "n. 鲨鱼"},
    { word: "van", definition: "n. 面包车"},
    { word: "lip", definition: "n. 嘴唇"},
    { word: "tall", definition: "adj. 高的"},
    { word: "flag", definition: "n. 旗"},
    { word: "aisle", definition: "n. 过道"},
    { word: "pet", definition: "n. 宠物"},
    { word: "vet", definition: "n. 兽医"},
    { word: "boost", definition: "v. 促进"},
    { word: "glove", definition: "n. 手套"},
    { word: "chef", definition: "n. 厨师"},
    { word: "smog", definition: "n. 烟雾"},
    { word: "inch", definition: "n. 英寸"},
    { word: "write", definition: "v. 写，写作"},
    { word: "sheep", definition: "n. 羊，绵羊"},
    { word: "huge", definition: "adj. 巨大的"},
    { word: "ice", definition: "n. 冰"},
    { word: "cream", definition: "n. 奶油"},
    { word: "harm", definition: "n./v. 伤害，损害"},
    { word: "inn", definition: "n. 小旅馆"},
    { word: "kit", definition: "n. 成套工具"},
    { word: "hug", definition: "v./n. 拥抱"},
    { word: "crew", definition: "n. 全体船员"},
    { word: "knock", definition: "v./n. 敲"},
    { word: "chalk", definition: "n. 粉笔"},
    { word: "lab", definition: "n. 实验室"},
    { word: "grade", definition: "n. 等级"},
    { word: "new", definition: "adj. 新的"},
    { word: "noon", definition: "n. 中午，正午"},
    { word: "kite", definition: "n. 风筝"},
    { word: "grey/gray", definition: "n./adj. 灰色(的)"},
    { word: "slice", definition: "n. 片"},
    { word: "knife", definition: "n. 刀"},
    { word: "hat", definition: "n. 帽子"},
    { word: "half", definition: "n./adj./adv. 一半(的)/(地)"},
    { word: "gramme", definition: "n. 克(重量单位)"},
    { word: "nest", definition: "n. 窝，巢，穴"},
    { word: "grape", definition: "n. 葡萄"},
    { word: "carve", definition: "v. 雕刻"},
    { word: "great", definition: "adj. 伟大的"},
    { word: "none", definition: "pron. 没有一个"},
    { word: "choke", definition: "n./v. 窒息"},
    { word: "lock", definition: "v./n. 锁"},
    { word: "lunch", definition: "n. 午餐"},
    { word: "mix", definition: "v. 混合"},
    { word: "month", definition: "n. 月；月份"},
    { word: "moon", definition: "n. 月球；月亮"},
    { word: "bread", definition: "n. 面包"},
    { word: "steel", definition: "n. 钢铁"},
    { word: "wheat", definition: "n. 小麦"},
    { word: "swear", definition: "v./n. 发誓"},
    { word: "breath", definition: "n. 呼吸"},
    { word: "breathe", definition: "v. 呼吸"},
    { word: "bowl", definition: "n. 碗"},
    { word: "bridge", definition: "n. 桥"},
    { word: "brick", definition: "n. 砖块，砖"},
    { word: "shirt", definition: "n. 衬衫"},
    { word: "brown", definition: "n./adj. 棕色(的)"},
    { word: "horse", definition: "n. 马"},
    { word: "knee", definition: "n. 膝盖"},
    { word: "luck", definition: "n. 好运"},
    { word: "wall", definition: "n. 墙，围墙"},
    { word: "brake", definition: "n./v. 刹车"},
    { word: "pink", definition: "n./adj. 粉红色(的)"},
    { word: "pub", definition: "n. 酒吧，酒馆"},
    { word: "rice", definition: "n. 大米"},
    { word: "pal", definition: "n. 朋友"},
    { word: "son", definition: "n. 儿子"},
    { word: "queen", definition: "n. 女王"},
    { word: "song", definition: "n. 歌曲"},
    { word: "hell", definition: "n. 地狱"},
    { word: "soup", definition: "n. 汤"},
    { word: "drill", definition: "v./n. 钻"},
    { word: "quick", definition: "adj./adv. 快的(的)，迅速的(地)"},
    { word: "read", definition: "v. 阅读"},
    { word: "choose", definition: "v. 选择"},
    { word: "sail", definition: "v. 航行 n. 帆"},
    { word: "shave", definition: "v. 剃须"},
    { word: "chore", definition: "n. 家务活"},
    { word: "snake", definition: "n. 蛇"},
    { word: "chop", definition: "v. 切碎"},
    { word: "goat", definition: "n. 山羊"},
    { word: "gate", definition: "n. 门口"},
    { word: "clap", definition: "v./n. 鼓掌"},
    { word: "quite", definition: "adv. 完全，十分"},
    { word: "skate", definition: "v. 滑冰"},
    { word: "dive", definition: "v./n. 潜水"},
    { word: "doll", definition: "n. 玩偶"},
    { word: "cow", definition: "n. 母牛"},
    { word: "drum", definition: "n. 鼓"},
    { word: "clay", definition: "n. 黏土"},
    { word: "cough", definition: "v./n. 咳嗽"},
    { word: "flame", definition: "n. 火焰"},
    { word: "game", definition: "n. 游戏"},
    { word: "duck", definition: "n. 鸭子"},
    { word: "fetch", definition: "v. 拿来"},
    { word: "film", definition: "n. 电影"},
    { word: "floor", definition: "n. 地板"},
    { word: "smoke", definition: "n. 烟 v. 吸烟"},
    { word: "depth", definition: "n. 深度"},
    { word: "deep", definition: "adj. 深的"},
    { word: "deer", definition: "n. 鹿"},
    { word: "first", definition: "adj./adv./n./pron. 第一(的)/(地)"},
    { word: "hot", definition: "adj. 热"},
    { word: "fox", definition: "n. 狐狸"},
    { word: "death", definition: "n. 死亡"},
    { word: "date", definition: "n. 日期"},
    { word: "fish", definition: "n. 鱼"},
    { word: "damp", definition: "adj. 潮湿的"},
    { word: "tea", definition: "n. 茶"},
    { word: "full", definition: "adj. 满的"},
    { word: "frog", definition: "n. 青蛙"},
    { word: "dance", definition: "n./v. 跳舞"},
    { word: "drawer", definition: "n. 抽屉"},
    { word: "think", definition: "v. 认为，想；思考"},
    { word: "smile", definition: "n./v. 微笑"},
    { word: "slim", definition: "adj. 苗条的"},
    { word: "fist", definition: "n. 拳头"},
    { word: "say", definition: "v. 说"},
    { word: "find", definition: "v. 找，找到"},
    { word: "foot", definition: "n. 脚"},
    { word: "loaf", definition: "n. 一条面包"},
    { word: "gay", definition: "adj. 快乐的"},
    { word: "sing", definition: "v. 唱歌"},
    { word: "frost", definition: "n. 霜"},
    { word: "wheel", definition: "n. 轮，车轮 v. 转动，旋转"},
    { word: "chess", definition: "n. 棋，国际象棋"},
    { word: "snow", definition: "n./v. 雪；降雪"},
    { word: "sad", definition: "adj. 悲哀的，难过的"},
    { word: "die", definition: "v. 死，消亡"},
    { word: "see", definition: "v. 看见；明白"},
    { word: "weak", definition: "adj. 软弱的"},
    { word: "mouth", definition: "n. 嘴；口"},
    { word: "chew", definition: "v. 咀嚼"},
    { word: "mouse", definition: "n. 老鼠；鼠标"},
    { word: "street", definition: "n. 街道"},
    { word: "price", definition: "n. 价格"},
    { word: "war", definition: "n. 战争；冲突"},
    { word: "cave", definition: "n. 洞，穴"},
    { word: "breast", definition: "n. 胸部；胸脯"},
    { word: "strait", definition: "n. 海峡"},
    { word: "stream", definition: "n. 溪，小河 v. 流，流动"},
    { word: "string", definition: "n. 线；一串"},
    { word: "cook", definition: "v. 烹饪 n. 厨师"},
    { word: "comb", definition: "n. 梳子 v. 梳，梳理"},
    { word: "grass", definition: "n. 草；草地"},
    { word: "guy", definition: "n. 男人"},
    { word: "lamb", definition: "n. 羔羊；小羊"},
    { word: "stir", definition: "v./n. 搅拌，搅动"},
    { word: "wet", definition: "adj. 湿的 v. 弄湿"},
    { word: "size", definition: "n. 大小，尺寸，规模"},
    { word: "fly", definition: "v. 飞 n. 苍蝇"},
    { word: "dry", definition: "adj. 干的 v. (使)变干"},
    { word: "hear", definition: "v. 听见；听"},
    { word: "hole", definition: "n. 洞；孔"},
    { word: "sleeve", definition: "n. 袖子"},
    { word: "kill", definition: "v. 杀死；消磨(时间)"},
    { word: "fat", definition: "n. 脂肪 adj.胖的"},
    { word: "few", definition: "pron. 很少几个，几乎没有"},
    { word: "dish", definition: "n. 菜肴；碟；盘"},
    { word: "draft", definition: "n. 草稿 v.起草"},
    { word: "all", definition: "pron./adv./adj./n. 所有，全部"},
    { word: "soil", definition: "n. 泥土，土地，土壤"},
    { word: "school", definition: "n. 学校 v.教育，培养"},
    { word: "far", definition: "adj./adv. 远的(地)"},
    { word: "roll", definition: "v. 滚动；卷起 n. 卷；名单"},
    { word: "egg", definition: "n. 鸡蛋；卵"},
    { word: "flu", definition: "n. 流感"},
    { word: "fog", definition: "n. 雾"},
    { word: "fork", definition: "n. 叉"},
    { word: "site", definition: "n. 现场；网站；站点"},
    { word: "face", definition: "n. 脸 v. 面对"},
    { word: "tick", definition: "n. 滴答声；对号 v. 发出滴答声；打勾号"},
    { word: "aid", definition: "n./v. 帮助，救援"},
    { word: "sum", definition: "n. 总数，和；金额 v. 合计，总计"},
    { word: "fee", definition: "n. 费(会费，学费等)"},
    { word: "bring", definition: "v. 拿来，带来；引起"},
    { word: "dear", definition: "adj. 亲爱的，昂贵的"},
    { word: "else", definition: "adv. 其他；另外 adj. 别的"},
    { word: "show", definition: "n. 节目，表演 v. 显示；表明"},
    { word: "art", definition: "n. 艺术；文科"},
    { word: "cap", definition: "n. 帽；盖，罩 v. 覆盖于......顶端"},
    { word: "put", definition: "v. 放，搁；说，表达；记下"}
],
window.weekWords.Week3 = [
    { word: "age", definition: "n. 年龄；时代 v. (使)变老"},
    { word: "strange", definition: "adj. 奇怪的；陌生的"},
    { word: "lead", definition: "v. 领导；导致 n. 带领；铅"},
    { word: "test", definition: "n./v. 试验；检验"},
    { word: "lie", definition: "v. 躺，位于 v. 说谎 n. 谎话"},
    { word: "loud", definition: "adj. 大声的，响亮的；吵闹的"},
    { word: "eye", definition: "n. 眼(睛)；视力 v. 看，审视"},
    { word: "log", definition: "v. 记录；登录 n. 日志；原木"},
    { word: "head", definition: "n. 头；领导，首脑 v. 主管"},
    { word: "break", definition: "v. 打破；违反 n. 休息时间"},
    { word: "smart", definition: "adj. 聪明的；时髦的"},
    { word: "try", definition: "v. 尝试；试用；审讯 n. 尝试"},
    { word: "seek", definition: "v. 寻找，探索；试图，企图"},
    { word: "like", definition: "v. 喜欢 prep. 像；比如 adj. 相像的"},
    { word: "alike", definition: "adj. 同样的，相像的 adv. 一样地"},
    { word: "path", definition: "n. 小路；路线"},
    { word: "small", definition: "adj. 小的；年幼的；不重要的"},
    { word: "pass", definition: "v. 经/通/穿/度过 n. 通过"},
    { word: "fool", definition: "adj. 愚蠢的 n. 傻瓜 v. 欺骗"},
    { word: "home", definition: "n./adj./adv. 家(的)/(地)"},
    { word: "steam", definition: "n. 水蒸气 v. 蒸"},
    { word: "man", definition: "n. 人；人类；男人"},
    { word: "surf", definition: "v. 冲浪，浏览"},
    { word: "bank", definition: "n. 银行；岸，堤"},
    { word: "sleep", definition: "v./n. 睡觉，睡眠"},
    { word: "host", definition: "v. 主持 n. 主人；主持人"},
    { word: "rift", definition: "n. 分裂，裂口"},
    { word: "dress", definition: "n. 衣服 v. 穿衣服"},
    { word: "cut", definition: "v. 切，消减"},
    { word: "way", definition: "n. 道路，方法/式，手段"},
    { word: "cry", definition: "v./n. 哭泣，哭喊声"},
    { word: "gap", definition: "n. 差距；空白；缺乏"},
    { word: "dull", definition: "adj. 单调的；迟钝的，愚笨的"},
    { word: "gas", definition: "n. 气体；煤气；汽油；毒气"},
    { word: "book", definition: "n. 书 v. 预订"},
    { word: "role", definition: "n. 角色，作用，任务，职责"},
    { word: "hold", definition: "v. 拿着；举行；认为 n. 握住"},
    { word: "drag", definition: "v. 拖，拽"},
    { word: "drug", definition: "n. 药品；麻醉品；毒品 v. 吸毒"},
    { word: "root", definition: "n. 根，根部；根本 v. (使)生根"},
    { word: "soul", definition: "n. 灵魂，心灵；精神"},
    { word: "broad", definition: "adj. 宽的，广阔的；广大的"},
    { word: "sure", definition: "adj. 肯定的 adv. 当然；确实"},
    { word: "fail", definition: "v. 失败，不及格；衰退"},
    { word: "warm", definition: "adj. 温暖的，热心的 v. (使)变暖"},
    { word: "back", definition: "adj. 后面的 adv. 向后 v. 倒退；支持 n.后面"},
    { word: "play", definition: "v. 玩，做游戏 n.游戏；剧本"},
    { word: "call", definition: "v. 称呼；喊；打电话 n. 叫；打电话"},
    { word: "sale", definition: "n. 出售；廉价出售"},
    { word: "fair", definition: "adj. 公平的，合理的；相当的 n. 集市"},
    { word: "strong", definition: "adj. 强壮的；强烈的，浓的"},
    { word: "end", definition: "n. 末端；目标，目的 v. 终止，结束"},
    { word: "vast", definition: "adj. 巨大的，辽阔的，大量的；巨额的"},
    { word: "tell", definition: "v. 告诉，讲述；辨别，区别"},
    { word: "aim", definition: "n. 目标，目的 v. 目的在于；瞄准"},
    { word: "fast", definition: "adj./adv. 快速的(地)"},
    { word: "watch", definition: "v. 观看；看守 n. 注视；手表；守护"},
    { word: "child", definition: "n. 儿童，儿，女"},
    { word: "smooth", definition: "adj. 光滑的；顺利的"},
    { word: "main", definition: "adj. 主要的，总的 n. 总管道；干线"},
    { word: "draw", definition: "v. 拉动；画；吸引 n. 平局；抽签"},
    { word: "rent", definition: "v. 租，租赁 n. 租金"},
    { word: "green", definition: "adj./n. 绿色(的)"},
    { word: "arch", definition: "n. 拱，拱行门"},
    { word: "look", definition: "v./n. 看 v. 好像，显得 n. 外表，脸色"},
    { word: "live", definition: "v. 活着，生活，居住 adj. 活的，现场直播的"},
    { word: "spot", definition: "n. 斑点；地点 v. 认出，发现；玷污，弄脏"},
    { word: "cell", definition: "n. 细胞；小房间；电池"},
    { word: "bad", definition: "adj. 坏的；腐败的"},
    { word: "dead", definition: "adj. 死的"},
    { word: "rude", definition: "adj. 粗鲁的"},
    { word: "join", definition: "v. 参加，加入；连接"},
    { word: "soft", definition: "adj. 软的；温柔的；光滑的"},
    { word: "jam", definition: "n. 阻塞；果酱 v.(使)阻塞"},
    { word: "care", definition: "n. 小心；关怀，照料 v. 关心"},
    { word: "goal", definition: "n. 目的，目标；进球得分"},
    { word: "heart", definition: "n. 心(脏)；内心；中心，要点"},
    { word: "light", definition: "n. 光；灯 v. 点燃；照亮 adj.轻(快)的；淡的"},
    { word: "odd", definition: "adj. 奇怪的；临时的；奇数的"},
    { word: "miss", definition: "v. 错过；思念"},
    { word: "take", definition: "v. 拿取；吃；花费；需要"},
    { word: "lose", definition: "v. 丢失，输掉，失败"},
    { word: "let", definition: "v. 让"},
    { word: "skip", definition: "v. 略过，跳过，忽略 n. 跳跃"},
    { word: "yard", definition: "n. 院子，场地；码"},
    { word: "drop", definition: "n. 滴；下降，减少 v. 落下；下降"},
    { word: "mad", definition: "adj. 发疯的；狂热的；生气的"},
    { word: "belt", definition: "n. 腰带，地带"},
    { word: "fond", definition: "adj. 喜爱的，爱好的"},
    { word: "stay", definition: "v. 逗留；保持 n. 逗留，停留"},
    { word: "tree", definition: "n. 树木"},
    { word: "work", definition: "n. 工作；作品 v. 工作；起作用"},
    { word: "teach", definition: "v. 教，教授"},
    { word: "pull", definition: "v. 拉，拖"},
    { word: "prove", definition: "v. 证明，证实；证明是，显示是"},
    { word: "gift", definition: "n. 礼物，天才，天赋"},
    { word: "talk", definition: "n. 谈话；聊天；讲话 v. 说话；交谈"},
    { word: "house", definition: "n. 房屋 v. 给……房子住"},
    { word: "wing", definition: "n. 翅膀；机翼；侧翼；派别"},
    { word: "hit", definition: "v. 打，击 n. 击中；风行一时的事物"},
    { word: "tip", definition: "n. 建议；尖端；小费 n./v. 轻击；倾斜；给小费"},
    { word: "fit", definition: "v. 合适，安装 adj.健康的；合适的 n. 疾病发作，一阵"},
    { word: "threat", definition: "n. 威胁，恐吓"},
    { word: "keen", definition: "adj. 锋利的；敏锐的；热心的，渴望的"},
    { word: "leak", definition: "v. 漏，泄漏 n. 漏洞；泄漏"},
    { word: "seize", definition: "v. 抓住，逮住；夺取，占领"},
    { word: "pay", definition: "v. 付款，付出代价 n. 工资，薪金"},
    { word: "sit", definition: "v. 坐，位于"},
    { word: "speak", definition: "v. 说话，讲话；演说"},
    { word: "bake", definition: "v. 烤，烘，焙"},
    { word: "wish", definition: "v. 但愿；祝 n. 愿望，希望"},
    { word: "mine", definition: "pron. 我的 n. 矿；地雷 v.采矿"},
    { word: "get", definition: "v. 得到；使；变得，成为；到达"},
    { word: "walk", definition: "v. 走，步行 n. 走；徒步旅行"},
    { word: "make", definition: "v. 制造，使变得 n. 品牌，型号"},
    { word: "free", definition: "adj. 自由的；免费的；空闲的 v. 释放"},
    { word: "west", definition: "n./adj. 西，西方(的)，西部(的) adv. 向西"},
    { word: "cure", definition: "v. 治愈，医治 n. 治愈；良药"},
    { word: "own", definition: "v. 拥有 adj. 自己的"},
    { word: "stage", definition: "n. 舞台；阶段，时期"},
    { word: "fight", definition: "v./n. 打(仗)，斗争，战斗"},
    { word: "true", definition: "adj. 真实的；正确的 adv. 真实地，准确的"},
    { word: "oil", definition: "n. 油，石油 v. 涂油，上油"},
    { word: "long", definition: "adj. 长的 adv. 长久，长期地"},
    { word: "blue", definition: "adj. 蓝色的；忧郁的 n. 蓝色"},
    { word: "skill", definition: "n. 技能，技巧，手艺"},
    { word: "wild", definition: "adj. 野生的；野蛮的；狂热的"},
    { word: "line", definition: "n. 线；路线，航线；界线 v. 排队"},
    { word: "reach", definition: "v. 抵达；够到 n. 能达到的范围"},
    { word: "fear", definition: "v. 畏惧，害怕，担心 n. 害怕，恐惧"},
    { word: "class", definition: "n. 班；种类；等级，阶级；课"},
    { word: "catch", definition: "v. 捕捉；赶上；感染；理解，听到"},
    { word: "whole", definition: "n. 全部；完整 adj. 全体的；全部的"},
    { word: "sick", definition: "adj. 有病的；恶心的"},
    { word: "feel", definition: "v. 感觉到；摸起来；觉得"},
    { word: "lay", definition: "v. 放，搁；下(蛋)；铺设"},
    { word: "due", definition: "adj. 到期的；预期的；应支付的"},
    { word: "pure", definition: "adj. 纯的，纯洁的；完全的"},
    { word: "hand", definition: "n. 手；指针 v. 交给"},
    { word: "worse", definition: "adj./adv. 更坏，更差(的/地)"},
    { word: "chance", definition: "n. 机会；运气 v. 碰巧，偶然发生"},
    { word: "hall", definition: "n. 礼堂，会堂；门厅"},
    { word: "fresh", definition: "adj. 新鲜的；无经验的"},
    { word: "spare", definition: "adj. 多余的，备用的 v. 节约；抽出(时间)"},
    { word: "suit", definition: "v. 合适；相配 n. 一套西服；诉讼"},
    { word: "cloth", definition: "n. 布，织物，衣料"},
    { word: "fault", definition: "n. 过失，过错；缺点，毛病"},
    { word: "staff", definition: "n. 全体职工"},
    { word: "fix", definition: "v. (使)固定；修理；安装；注视"},
    { word: "spring", definition: "n. 春；跳；泉；弹簧 v. 跳，跳跃"},
    { word: "folk", definition: "n. 人们 adj. 民间的"},
    { word: "aunt", definition: "n. 阿姨，姑母，姨母"},
    { word: "ham", definition: "n. 火腿"},
    { word: "crop", definition: "n. 作物，庄稼"},
    { word: "fare", definition: "n. 车费，船费"},
    { word: "ray", definition: "n. 光线，射线"},
    { word: "joy", definition: "n. 欢乐，喜悦"},
    { word: "boil", definition: "v. (使)沸腾，煮 ()"},
    { word: "fill", definition: "v. 填满，充满"},
    { word: "beach", definition: "n. 海滩，沙滩"},
    { word: "crime", definition: "n. 罪行，犯罪"},
    { word: "brave", definition: "adj. 勇敢的"},
    { word: "leaf", definition: "n. 叶子；一页，一张"},
    { word: "check", definition: "v. 检查；制止 n. 检查；支票"},
    { word: "lift", definition: "v. 升起 n. 电梯；上升；免费搭车"},
    { word: "pace", definition: "n. 步，步调，速度 v. 踱步，用步测"},
    { word: "each", definition: "adj./pron. 各，各自的，每"},
    { word: "cheat", definition: "v. 欺骗；作弊 n. 骗子；欺诈"},
    { word: "owe", definition: "v. 欠(债等)；归功于"},
    { word: "fall", definition: "v. 跌倒；下降；变成 n. 秋季(autumn)"},
    { word: "wind", definition: "n. 风 v. 上发条；蜿蜒而行"},
    { word: "coin", definition: "n. 硬币 v. 创造(新词)，铸造(硬币)"},
    { word: "such", definition: "adj. 这样的 adv. 那么 pron. 这样的人(事物)"},
    { word: "round", definition: "adj. 圆的 prep.围绕"},
    { word: "brith", definition: "n. 出生；出身；出现"},
    { word: "still", definition: "adj. 静止的，寂静的 adv. 仍然；更；安静地"},
    { word: "solve", definition: "v. 解决，处理"},
    { word: "cheer", definition: "v. (使)振奋 v./n. 喝彩，欢呼"},
    { word: "high", definition: "adj. 高的；高级的 adv. 高高地"},
    { word: "push", definition: "v. 推；逼迫 n. 推力；促进"},
    { word: "snack", definition: "n. 快餐，小吃"},
    { word: "fund", definition: "n. 资金，基金"},
    { word: "clear", definition: "adj. 清楚的 v. 清除"},
    { word: "low", definition: "adj. 低，矮；低级的"},
    { word: "slight", definition: "adj. 轻微的，微小的"},
    { word: "skirt", definition: "n. 裙子；边缘，郊区"},
    { word: "choice", definition: "n. 选择，抉择 adj. 精选的"},
    { word: "last", definition: "v. 持续 adj. 最后的 adv. 最后 n.最后"},
    { word: "box", definition: "n. 盒，箱 v. 拳击；打耳光"},
    { word: "step", definition: "n. 步；台阶；步骤，措施 v. 踏，走"},
    { word: "urge", definition: "v. 催促；促进 n. 强烈欲望"},
    { word: "drive", definition: "v. 开(车)；驱动 n. 驾驶"},
    { word: "grasp", definition: "v./n. 抓住；掌握"},
    { word: "hurt", definition: "n. 伤痛，伤害 v. 刺痛，伤害"},
    { word: "link", definition: "v. 连接，联系 n. 环节"},
    { word: "firm", definition: "n. 公司 adj. 坚固的；坚决的"},
    { word: "loan", definition: "v./n. 贷款；借出"},
    { word: "cross", definition: "v. 交叉 n. 十字架"},
    { word: "grow", definition: "v. 生长；渐渐变成；种植"},
    { word: "claim", definition: "v./n. 要求；声称；索赔"},
    { word: "ill", definition: "adj. 有病的；坏的"},
    { word: "slow", definition: "adj. 慢的 v. 放慢，减速"},
    { word: "pair", definition: "n. 一对，一双；一副；夫妇 v. 成对"},
    { word: "dign", definition: "n. 标记；征兆，迹象 v. 签名"},
    { word: "rush", definition: "v. 冲；奔 n. 冲 adj. (交通)繁忙的"},
    { word: "send", definition: "v. 打发；派遣，发送"},
    { word: "crowd", definition: "n. 人群；一群，一伙 v. 聚集；拥挤"},
    { word: "shout", definition: "v./n. 呼叫，呼喊"},
    { word: "quit", definition: "v. 离开；停止；放弃；辞职"},
    { word: "bite", definition: "v./n. 咬，叮 n. 一口"},
    { word: "pick", definition: "v. 拾，采，摘；挑选，选择"},
    { word: "shop", definition: "n. 商店 v. 逛商店"},
    { word: "bend", definition: "v. (使)弯曲 n. 弯曲"},
    { word: "worth", definition: "n. 价值，重要性 adj. 值得……的"},
    { word: "shock", definition: "n. 电击；休克；冲击，撞击 v. (使)震惊"},
    { word: "false", definition: "adj. 假的，虚伪的"},
    { word: "gain", definition: "v. 获得；增加 n. 增加；收益"},
    { word: "safe", definition: "adj. 安全的 n. 保险箱"},
    { word: "click", definition: "v. (用鼠标)点击 n. 单击"},
    { word: "use", definition: "v. 应用，使用"},
    { word: "bound", definition: "adj. 受到约束的；一定的 v./n. 跳(跃)"},
    { word: "plus", definition: "prep. 加 conj. 此外"},
    { word: "scan", definition: "v. 扫描；浏览；审视 n. 扫描"},
    { word: "short", definition: "adj. 短的，矮的；缺乏的"},
    { word: "rich", definition: "adj. 富的；充足的，丰富的"},
    { word: "near", definition: "adj. 近的 prep. 靠近 adv. 接近"},
    { word: "set", definition: "n. 一套，一副，装置 v. 设置；使开始；日落"},
    { word: "cause", definition: "n. 原因；事业 v. 引起"},
    { word: "state", definition: "n. 状态，情况；国，州 v. 陈述，说明"},
    { word: "chair", definition: "n. 椅子；主席 v. 当……的主席，主持"},
    { word: "pain", definition: "n. 痛苦；(pl.)努力 v. 使努力"},
    { word: "shift", definition: "v. 转移；变换，变动 n. 转变；(轮)班"},
    { word: "nod", definition: "v. 点头示意；打盹 n. 点头"},
    { word: "earn", definition: "v. 赚得，获得"},
    { word: "kind", definition: "adj. 仁慈的，友好的 n. 种类"},
    { word: "sight", definition: "n. 视力；眼界"},
    { word: "hard", definition: "adj. 坚硬的；结实的；困难的"},
    { word: "blind", definition: "adj. 盲的；盲目的 n. 百叶窗"},
    { word: "chief", definition: "adj. 主要的 n. 首领，领袖"},
    { word: "stop", definition: "v. 停止；阻止 n. 停车站；停止"},
    { word: "truth", definition: "n. 真相，事实"},
    { word: "born", definition: "adj. 出生的；天生的"},
    { word: "frank", definition: "adj. 坦白的，直率的"},
    { word: "ease", definition: "v. 减轻；使舒适 n. 容易；舒适"},
    { word: "black", definition: "adj. 黑的；黑暗的 n. 黑；黑暗"},
    { word: "wide", definition: "adj. 宽阔的 adv. 广阔地"},
    { word: "flow", definition: "v. 流，流动 n. 流量，流速"},
    { word: "trade", definition: "n. 贸易；职业，行业 v. 经商，交易"},
    { word: "clam", definition: "adj. 平静的 v. (使)平静"},
    { word: "speed", definition: "n. 速度 v. 迅速；加速"},
    { word: "zoom", definition: "v. 快速移动 n. 猛增"},
    { word: "twice", definition: "adv. 两次，两倍"},
    { word: "wage", definition: "n. (常pl.)工资，报酬"},
    { word: "stuff", definition: "n. 原料，材料，东西 v. 填满，塞满"},
    { word: "youth", definition: "n. 青年，年轻人"},
    { word: "nail", definition: "n. 指甲；钉子"},
    { word: "storm", definition: "n. 暴风雨，暴风雪"},
    { word: "right", definition: "adj. 右的；正确的 n. 右；权利 adv. 在右边；正确地"},
    { word: "dark", definition: "adj. 黑的，深(色)的"},
    { word: "trail", definition: "n. 小路"},
    { word: "club", definition: "n. 社团；球棒；夜总会"},
    { word: "word", definition: "n. 词；消息 v. 措辞，用词"},
    { word: "bear", definition: "n. 熊 v. 忍受；负担；结果实，生子女"},
    { word: "tense", definition: "adj. 紧张的 n. 时态"},
    { word: "sense", definition: "n. 感觉；意义；道理 v. 觉得，意识到"},
    { word: "tour", definition: "n. 旅游；巡回演出/比赛 v. 旅游"},
    { word: "change", definition: "n./v. 改变，变化 n. 零钱"},
    { word: "form", definition: "n. 形状，形式；表格 v. 组成；形成"},
    { word: "stare", definition: "v./n. 盯，凝视"},
    { word: "bill", definition: "n. 账单；议案，法案；钞票"},
    { word: "tend", definition: "v. 趋向，往往是；照料，看护"},
    { word: "route", definition: "n. 路线，路程"},
    { word: "bright", definition: "adj. 明亮的；聪明的；欢快的"},
    { word: "spray", definition: "n. 喷雾 v. 喷"},
    { word: "mood", definition: "n. 心情，情绪；语气"},
    { word: "weed", definition: "n. 杂草"},
    { word: "park", definition: "n. 公园；停车场 v. 停车"},
    { word: "square", definition: "n. 正方形；广场 adj. 正方形的"},
    { word: "row", definition: "n. 排，行；吵嚷 v. 划(船等)"},
    { word: "stamp", definition: "n. 邮票；印"},
    { word: "phase", definition: "n. 阶段，时期"},
    { word: "name", definition: "n. 名字 v. 列举；提名"},
    { word: "mere", definition: "adj. 仅仅，只不过"},
    { word: "thought", definition: "n. 想法"},
    { word: "mild", definition: "adj. 温和的，轻微的"},
    { word: "thread", definition: "n. 线"},
    { word: "rough", definition: "adj. 粗糙的；大致的"},
    { word: "time", definition: "n. 时间；次；时代；倍，乘"},
    { word: "code", definition: "n. 代码，密码；法典，法规"},
    { word: "bore", definition: "v. 烦扰；钻(孔) n. 讨厌的人，麻烦事"},
    { word: "net", definition: "n. 网 adj. 净重的 v. 用网捕"},
    { word: "seed", definition: "n. 种子"},
    { word: "world", definition: "n. 世界；界，领域"},
    { word: "wealth", definition: "n. 财富，财产"},
    { word: "though", definition: "conj. 虽然，尽管 adv. 不过，然而"},
    { word: "troop", definition: "n. 队伍，部队"},
    { word: "hook", definition: "n. 钩，吊钩 v. 钩住"},
    { word: "sharp", definition: "adj. 锋利的 adv. (指时刻)正"},
    { word: "brand", definition: "n. 品牌，牌子"},
    { word: "score", definition: "n. 得分，分数；二十 v. 得(分)"}
],
window.weekWords.Week4 = [
    { word: "lack", definition: "n./v. 缺乏，不足"},
    { word: "soap", definition: "n. 肥皂"},
    { word: "team", definition: "n. 小队，小组"},
    { word: "task", definition: "n. 任务，作业"},
    { word: "proof", definition: "n. 证据，证明"},
    { word: "raw", definition: "adj. 生的；未加工过的"},
    { word: "plain", definition: "adj. 明白的；朴素的 n. 平原"},
    { word: "clue", definition: "n. 线索，暗示"},
    { word: "point", definition: "n. 尖；点；分数 v. 指"},
    { word: "course", definition: "n. 课程；过程；路线；一道菜"},
    { word: "treat", definition: "v. 对待；治疗；请客；把……视为 n. 款待，请客"},
    { word: "throw", definition: "v. 扔；使突然陷入"},
    { word: "sauce", definition: "n. 酱；调味汁"},
    { word: "rap", definition: "n. 说唱 v. 敲击"},
    { word: "clone", definition: "n. 无性繁殖，克隆；复制品 v. 克隆"},
    { word: "pour", definition: "v. 倾泻，倾盆大雨"},
    { word: "slip", definition: "n. 疏忽，小错；滑动；小纸条 v. 滑倒；溜走"},
    { word: "waste", definition: "v. 浪费 adj. 无用的 n. 浪费；废物"},
    { word: "yet", definition: "adv. 还，仍然；已经；甚至 conj. 然而"},
    { word: "add", definition: "v. 加；进一步说"},
    { word: "bomb", definition: "n. 炸弹"},
    { word: "want", definition: "v. 想要；需要；缺少 n. 需要；短缺"},
    { word: "as", definition: "adv. 同样地 conj. 由于；像……一样 prep. 作为"},
    { word: "well", definition: "adv. 好；很 n. 井，水井"},
    { word: "till", definition: "prep. 直到……为止 v. 耕种；梨"},
    { word: "while", definition: "conj. 当……的时候；而；虽然；尽管 n. 一会儿"},
    { word: "thin", definition: "adj. 薄的；瘦的"},
    { word: "tear", definition: "n. 眼泪 v. 撕裂"},
    { word: "chain", definition: "n. 链(条)；一连串"},
    { word: "spell", definition: "v. 拼写，招致 n. 一段时间"},
    { word: "spend", definition: "v. 度过，花费"},
    { word: "meat", definition: "n. 肉，肉类"},
    { word: "shake", definition: "n./v. 摇动；颤抖，震动"},
    { word: "tough", definition: "adj. 艰难的，棘手的"},
    { word: "track", definition: "n. 跑道，小路；轨迹 v. 跟踪，跟随"},
    { word: "view", definition: "n. 视野；风景；见解 v. 观察；认为"},
    { word: "male", definition: "n./adj. 男性(的)，雄性(的)"},
    { word: "serve", definition: "v. 服务；招待；提供"},
    { word: "need", definition: "aux.v./v. 需要 n. 需要；缺乏"},
    { word: "melt", definition: "v./n. 溶化，融化"},
    { word: "press", definition: "v. 压；催促 n. 报刊，通讯社"},
    { word: "left", definition: "n./adj. 左边(的)"},
    { word: "east", definition: "n. 东；东部；东方"},
    { word: "south", definition: "n. 南，南部"},
    { word: "north", definition: "n. 北，北部"},
    { word: "buy", definition: "v. 买；相信"},
    { word: "block", definition: "n. 大块；街区；障碍物 v. 阻塞"},
    { word: "turn", definition: "v./n. (使)转动；(使)转变 n. 转弯，变化"},
    { word: "rise", definition: "v./n. 升起；上涨"},
    { word: "sun", definition: "n. 太阳；恒星"},
    { word: "leave", definition: "v. 离开；留下；让 n. 请假"},
    { word: "stair", definition: "n.(pl.) 楼梯；阶梯"},
    { word: "twin", definition: "adj. 双的，孪生的 n. 双胞胎，孪生子"},
    { word: "fan", definition: "n. 扇子，风扇；迷"},
    { word: "seat", definition: "n. 座位 v. 使坐下"},
    { word: "tag", definition: "n. 标签 v. 加标签于"},
    { word: "meal", definition: "n. 一餐；早(或午晚)餐"},
    { word: "length", definition: "n. 长；长度"},
    { word: "means", definition: "n. 方法；方式"},
    { word: "cent", definition: "n. 分(币)；百"},
    { word: "bond", definition: "n. 纽带。联系；结合(物)；债券"},
    { word: "scare", definition: "n. 惊恐，恐慌 v. 惊慌"},
    { word: "trust", definition: "v. 信任；委托 n. 信任；信托，托管"},
    { word: "voice", definition: "n. 声音；噪音；意见 v. 表达，发表"},
    { word: "down", definition: "adv. 下 prep. 沿着……而下 adj. 向下的"},
    { word: "soon", definition: "adv. 不久；快，早"},
    { word: "thick", definition: "adj./adv. 厚的(地)；粗的(地)；浓的(地)"},
    { word: "camp", definition: "n. 野营，营地；阵营 v. 设营，宿营"},
    { word: "share", definition: "v. 共享，分享 n. 一份；股份"},
    { word: "freeze", definition: "v. 使结冰，使凝固"},
    { word: "maths", definition: "n.(mathematics) 数学"},
    { word: "race", definition: "n. 比赛，赛跑；人种，种族 v. 赛跑"},
    { word: "dig", definition: "v. 挖，掘"},
    { word: "lane", definition: "n. 小路，行车道"},
    { word: "dust", definition: "n. 灰尘，尘土 v. 拂，掸"},
    { word: "store", definition: "n. 商店；储存，储备 v. 贮藏"},
    { word: "just", definition: "adv. 只是，仅仅；刚才；正好"},
    { word: "please", definition: "int. 请 v. 使满意"},
    { word: "least", definition: "adj./adv. 最小；最少"},
    { word: "risk", definition: "v. 冒……的危险 n. 冒险；风险"},
    { word: "tale", definition: "n. 故事，传说；描述，讲述"},
    { word: "place", definition: "n. 地方 v. 安排；放置"},
    { word: "peace", definition: "n. 和平；平静，安宁"},
    { word: "touch", definition: "v. 碰，摸；感动；涉及 n. 触动；少许"},
    { word: "clerk", definition: "n. 职员，办事员；店员"},
    { word: "lend", definition: "v. 借给；给予"},
    { word: "wake", definition: "v. 醒来，唤醒；激发，引起"},
    { word: "launch", definition: "v. 发射；发动，开展 n. 发射，下水"},
    { word: "hike", definition: "n. 徒步旅行；增加 v. 徒步旅行"},
    { word: "part", definition: "n. 部分；角色；一方 v. 使分开"},
    { word: "plane", definition: "n. 飞机"},
    { word: "plant", definition: "n. 植物 v. 种植"},
    { word: "shape", definition: "n. 形状，外形 v. 成型，塑造"},
    { word: "beat", definition: "n. 敲打；跳动 v. 打败；跳动；敲打"},
    { word: "mess", definition: "n. 混乱，混杂 v. 弄乱，搞糟"},
    { word: "trip", definition: "n. 旅行，远足"},
    { word: "plug", definition: "n. 插头，插座"},
    { word: "mail", definition: "n. 邮件"},
    { word: "tank", definition: "n. 罐，槽，箱；坦克 v. 储与槽中"},
    { word: "arm", definition: "n. 手臂；扶手 v. 武装；配备 n.(arms)武器"},
    { word: "room", definition: "n. 房间，空间；余地"},
    { word: "shy", definition: "adj. 害羞的，胆小的"},
    { word: "range", definition: "n. 范围；山脉 v. 在……范围内变动"},
    { word: "queue", definition: "n. 行列，长队 v. 排队"},
    { word: "peak", definition: "n. 山顶，最高点；山峰"},
    { word: "trace", definition: "n. 痕迹；极少量 v. 跟踪，追踪，寻找"},
    { word: "rock", definition: "n. 岩石；摇滚乐"},
    { word: "shoot", definition: "v. 拍摄；射击"},
    { word: "cite", definition: "v. 引用，引证，举(例)"},
    { word: "praise", definition: "v. 赞扬；表扬 n. 称赞，赞美"},
    { word: "ski", definition: "v. 滑雪"},
    { word: "tent", definition: "n. 帐篷"},
    { word: "swing", definition: "n. 秋千；摇摆，波动 v. 摇摆；影响"},
    { word: "sport", definition: "n. (体育)运动"},
    { word: "ring", definition: "n. 戒指；铃声 v. 给……打电话"},
    { word: "frame", definition: "n. 框架，架构"},
    { word: "scene", definition: "n. 景色；舞台；一场"},
    { word: "torch", definition: "n. 手电筒；火炬，火把"},
    { word: "mount", definition: "v. 登上；增加 n. 山峰"},
    { word: "tax", definition: "n. 税(款)"},
    { word: "tape", definition: "n. 磁带，胶带"},
    { word: "lean", definition: "v. 倾斜；倚，依赖 adj. 瘦的，无脂肪的"},
    { word: "drought", definition: "n. 旱灾，干旱"},
    { word: "roof", definition: "n. 屋顶，顶部"},
    { word: "march", definition: "v. (使)行军，(使)行进 n. 行军"},
    { word: "poll", definition: "n. 民意测验"},
    { word: "grant", definition: "v. 同意，准予；授予 n. 拨款"},
    { word: "grand", definition: "adj. 盛大的，豪华的；重大的"},
    { word: "fold", definition: "v. 折叠；合拢 n. 褶痕"},
    { word: "cease", definition: "v. 停止，中止"},
    { word: "road", definition: "n. 道路，途径"},
    { word: "cast", definition: "v. 投，扔；铸造；投票 n. 演员表"},
    { word: "vice", definition: "adj. 副的，代理的 n. 邪恶；恶习"},
    { word: "vote", definition: "n. 投票；选票，选票数 v. 投票，表决"},
    { word: "toast", definition: "n. 烤面包，吐司；祝酒(词) v. 烘，烤；(向……)祝酒"},
    { word: "craft", definition: "n. 工艺，手艺，技巧；飞机，飞船"},
    { word: "weep", definition: "v. 哭泣，流泪；摘下 n. 哭泣"},
    { word: "league", definition: "n. 同盟，联盟；联合会，社团"},
    { word: "stock", definition: "n. 库存，现货；股票，公债 v. 储存"},
    { word: "theme", definition: "n. 题目，主题；主旋律，基调"},
    { word: "plate", definition: "n. 盘子；板，板块"},
    { word: "edge", definition: "n. 边；刃；优势 v. 略微增加或减少"},
    { word: "tune", definition: "n. 调子，曲调 v. 调音，调节，调整"},
    { word: "field", definition: "n. 田野；运动场；领域"},
    { word: "type", definition: "n. 型式，类型 v. 打字"},
    { word: "file", definition: "n. 文件，档案；锉刀"},
    { word: "spit", definition: "v. 吐，唾"},
    { word: "sink", definition: "v. (使)下沉，下落 n. 水槽，水池"},
    { word: "sound", definition: "n. 声音 v. 听起来 adj. 健康的；合理的"},
    { word: "past", definition: "adj. 过去的 adv. 过去 prep. 超过"},
    { word: "heat", definition: "n. 热；热烈 v. (使)加热"},
    { word: "text", definition: "n. 正文，文本"},
    { word: "air", definition: "n. 空气；(pl.)神气 v. (使)通风"},
    { word: "count", definition: "v. 数，计算"},
    { word: "court", definition: "n. 法院，法庭；院子；球场"},
    { word: "lap", definition: "n. 大腿，(跑道的)一圈"},
    { word: "height", definition: "n. 高度；(常pl.)高地"},
    { word: "starve", definition: "v. 饿死；渴望"},
    { word: "pride", definition: "n. 自豪；自尊 v. 使自豪"},
    { word: "proud", definition: "adj. 自豪的；骄傲的"},
    { word: "bag", definition: "n. 袋，提包"},
    { word: "rate", definition: "n. 速率；等级价格，费用 v. 估价；评价"},
    { word: "cheese", definition: "n. 干酪，乳酪"},
    { word: "tone", definition: "n. 音调；气氛；腔调，语气；色调"},
    { word: "tap", definition: "n. 水龙头 n./v. 轻打，轻敲 v. 开发，利用"},
    { word: "pole", definition: "n. 柱，杆；地极，磁极，电极"},
    { word: "style", definition: "n. 方式，作风，风格，文本；类型"},
    { word: "mass", definition: "n. 大量，众多(pl.)群众，民众；质量"},
    { word: "news", definition: "n. 新闻；消息"},
    { word: "theft", definition: "n. 偷窃；偷窃罪"},
    { word: "switch", definition: "v. 转换 n. 开关"},
    { word: "quiz", definition: "n. 小型考试，测验"},
    { word: "gold", definition: "n. 金色；金黄 adj. 金色的"},
    { word: "mist", definition: "n. 薄雾"},
    { word: "blank", definition: "adj. 空白的 n. 空白；空格"},
    { word: "plot", definition: "n. 秘密计划；情节 v. 绘制；密谋，策划"},
    { word: "weigh", definition: "v. 称……重量，称；重达；考虑，权衡"},
    { word: "wipe", definition: "v. 擦，揩，抹"},
    { word: "rank", definition: "n. 军衔，社会阶层 v. 分等级"},
    { word: "mode", definition: "n. 方式，模式"},
    { word: "band", definition: "n. 条，带；乐队；一群，一伙"},
    { word: "source", definition: "n. 源泉；来源，出处"},
    { word: "shade", definition: "n. 荫，阴影；遮光物"},
    { word: "next", definition: "n./adv./adj. 下一个(的)/(地)"},
    { word: "strike", definition: "n./v. 罢工，打，击；给……深刻印象"},
    { word: "charge", definition: "v. 收费；控告；充电；主管 n. 费用，代价；电荷"},
    { word: "grain", definition: "n. 谷物，谷类；颗粒，细粒"},
    { word: "tie", definition: "n. 领带；关系 v. 扎，系，捆"},
    { word: "hunt", definition: "v./n. 打猎；搜索；寻找"},
    { word: "flight", definition: "n. 航班；飞行"},
    { word: "day", definition: "n. 天；白天；时期，时代"},
    { word: "niece", definition: "n. 侄女；外甥女"},
    { word: "board", definition: "n. 板；董事会 v. 上船(车，飞机)"},
    { word: "close", definition: "v. 关 adj. 密切的 adv. 接近"},
    { word: "star", definition: "n. 星；明星；恒星；主角"},
    { word: "bay", definition: "n. 海湾"},
    { word: "jaw", definition: "n. 颌，下巴"},
    { word: "then", definition: "adv. 然后；当时；于是"},
    { word: "flat", definition: "adj. 平的 n. 公寓；平地"},
    { word: "throught", definition: "prep./adv. 穿过；由，以"},
    { word: "stand", definition: "v. 站立；经受 n. 货摊；立场"},
    { word: "flood", definition: "n. 洪水 v. 淹没"},
    { word: "rule", definition: "n. 规章，条例；统治 v. 统治；支配；裁定"},
    { word: "sex", definition: "n. 性别，性"},
    { word: "golf", definition: "n. 高尔夫球运动"},
    { word: "spoil", definition: "v. 损坏；宠坏，溺爱"},
    { word: "raise", definition: "v. 举起；增加；饲养；引起；提出"},
    { word: "act", definition: "v. 表演；行为；起作用 n. 行为，法令"},
    { word: "eve", definition: "n. (节目等的)前夜，前夕"},
    { word: "top", definition: "n. 顶端；首位 adj. 最高的 v. 超越；达到顶点"},
    { word: "mate", definition: "n. 伙伴，同事，配偶 v. 配对，交配"},
    { word: "key", definition: "n. 钥匙；答案；关键；键 adj. 主要的，关键的"},
    { word: "meet", definition: "v. 遇见；会面；满足；符合"},
    { word: "mind", definition: "n. 思想，头脑 v. 介意"},
    { word: "sort", definition: "n. 种类，类别 v. 分类，整理"},
    { word: "kid", definition: "n. 小孩，儿童 v. 戏弄，取笑"},
    { word: "job", definition: "n. 工作；职责"},
    { word: "pause", definition: "v./n. 中止，暂停"},
    { word: "thus", definition: "adv. 因此，从而"},
    { word: "tin", definition: "n. 锡，罐头"},
    { word: "force", definition: "n. 力量；(pl.)(总称)军队 v. 强迫"},
    { word: "wrist", definition: "n. 手腕，腕关节"},
    { word: "learn", definition: "v. 学习，学会；获悉"},
    { word: "train", definition: "n. 列车；一串 v. 训练，培养"},
    { word: "trick", definition: "n. 诡计，骗局；恶作剧 v. 欺骗"},
    { word: "sake", definition: "n. 缘故，理由；目的，好处"},
    { word: "chart", definition: "n. 图表"},
    { word: "taste", definition: "v. 品尝；(of)有……味道 n. 滋味；品味"},
    { word: "bow", definition: "v./n. 鞠躬；点头 n. 弓(形)；蝴蝶结"},
    { word: "law", definition: "n. 法律，法学，规律，定律"},
    { word: "shame", definition: "n. 羞耻，耻辱；惋惜的事 v. 使羞愧"},
    { word: "guide", definition: "n. 指南，导游 v. 领路；指导"},
    { word: "ship", definition: "n. 船 v. 运输，船运"},
    { word: "smell", definition: "n. 气味；嗅觉 v. 闻到；散发气味"},
    { word: "mark", definition: "n. 痕迹；记号；分散 v. 标记，打分"},
    { word: "paint", definition: "n. 油漆，颜料 v. 涂装；画"},
    { word: "wear", definition: "v./n. 穿戴；磨损 n. 衣服"},
    { word: "list", definition: "n./v. 列表；清单"},
    { word: "coach", definition: "n. 长途汽车；教练 v. 训练，指导"},
    { word: "hide", definition: "v. 隐藏；隐瞒"}
],
window.weekWords.Week5 = [
    { word: "mean", definition: "v. 意味着 adj. 卑鄙的；平均的"},
    { word: "guard", definition: "v./n. 保卫 n. 警卫，看守"},
    { word: "sheet", definition: "n. 薄片，床单"},
    { word: "life", definition: "n. 生命，生活"},
    { word: "brain", definition: "n. (大)脑；(pl.)脑力"},
    { word: "wave", definition: "n. 波浪；挥手 v. (挥手)示意；摆动"},
    { word: "tide", definition: "n. 潮，潮汐；潮流，趋势"},
    { word: "health", definition: "n. 健康"},
    { word: "trap", definition: "n. 陷阱，圈套，诡计 v. 诱捕，设圈套"},
    { word: "shine", definition: "v. 闪耀，照耀"},
    { word: "move", definition: "v. 移动；提出，提议"},
    { word: "bar", definition: "n. 条，杆，闩；酒吧；障碍(物) v. 闩上，阻拦"},
    { word: "base", definition: "n. 基础，底部；根据地 v. 把……基于"},
    { word: "lake", definition: "n. 湖"},
    { word: "load", definition: "v. 装载，装(货) n. 装载(量)，负荷(量)"},
    { word: "post", definition: "v. 贴出；公告；发帖子 n. (支)柱；邮政；职位"},
    { word: "core", definition: "n. 果核；中心，核心"},
    { word: "swim", definition: "v./n. 游泳"},
    { word: "loose", definition: "v. 松开 adj. 宽松的"},
    { word: "lot", definition: "pron./det. 许多；大量"},
    { word: "stretch", definition: "v. 伸展，延伸 n. 拉长；伸展；一段时间/路程"},
    { word: "deal", definition: "v. 处理；经营，交易 n. 交易"},
    { word: "scale", definition: "n. 刻度；天枰；比例尺；规格"},
    { word: "span", definition: "n. 跨度，范围，时间跨度"},
    { word: "stone", definition: "n. 石头"},
    { word: "prize", definition: "n. 奖赏，奖品 v.珍惜，珍视"},
    { word: "sweet", definition: "adj. 甜的 n. 糖果，甜食"},
    { word: "mop", definition: "n. 拖把"},
    { word: "save", definition: "v. 救；储蓄；节省 prep. 除……之外"},
    { word: "sea", definition: "n. 海，海洋；大量"},
    { word: "win", definition: "v. 获胜；赢得；获得 n. 胜利"},
    { word: "faith", definition: "n. 信任；信仰"},
    { word: "ripe", definition: "adj. 熟的，成熟的"},
    { word: "term", definition: "n. 学期；术语 v. 把……称为"},
    { word: "spread", definition: "v./n. 伸展；散步，传播"},
    { word: "piece", definition: "n. (一)件/片/篇；碎片 v. 拼凑"},
    { word: "bat", definition: "n. 球拍，球棒；蝙蝠"},
    { word: "brief", definition: "adj. 简短的，简洁的 v. 简短介绍，简要汇报"},
    { word: "found", definition: "v. 建立；创立；创办"},
    { word: "screen", definition: "n. 屏幕；帘 v. 掩蔽，包庇；审查"},
    { word: "bath", definition: "n./v. 沐浴，洗澡"},
    { word: "pan", definition: "n. 平底锅，盘子"},
    { word: "greet", definition: "v. 打招呼；欢迎"},
    { word: "cash", definition: "n. 现金 v. 兑现，付(或收)现款"},
    { word: "cost", definition: "n. 成本，费用，代价 v. 花费"},
    { word: "stress", definition: "n. 压力；重要性；重音 v. 强调，重读"},
    { word: "prime", definition: "adj. 主要的，首要的"},
    { word: "glue", definition: "n. 胶 v. (用胶水)粘合"},
    { word: "batch", definition: "v. 孵出"},
    { word: "hair", definition: "n. 毛发，头发"},
    { word: "ride", definition: "v. 骑 n. 短途旅行"},
    { word: "chip", definition: "n. 芯片；缺口；油炸土豆条"},
    { word: "note", definition: "n. 笔记，便条 v. 记录，注意"},
    { word: "sore", definition: "adj. 疼痛的"},
    { word: "nurse", definition: "n. 护士 v. 看护"},
    { word: "once", definition: "adv. 一次，一旦，曾经 conj. 一旦……(就……)"},
    { word: "page", definition: "n. (书刊或纸张的)页"},
    { word: "pin", definition: "n. 大头针 v. 固定，别上"},
    { word: "group", definition: "n. 组 v. 把……分组"},
    { word: "cart", definition: "n. 手推车；运货马车"},
    { word: "front", definition: "n. 前面 adj. 在前的"},
    { word: "globe", definition: "n. 地球；世界"},
    { word: "global", definition: "adj. 全球的，全世界的；全面的"},
    { word: "cool", definition: "adj. 妙极的，凉爽的 v. (使)变凉"},
    { word: "fine", definition: "adj. 好的 n. 罚款 v. 处……以罚金"},
    { word: "crisp", definition: "adj. 脆的，凉爽的 n. 油炸土豆片"},
    { word: "case", definition: "n. 箱，盒；情况；病例；案件；例子"},
    { word: "rest", definition: "n. 休息；剩余部分 v. 休息"},
    { word: "rare", definition: "adj. 稀有的，难得的"},
    { word: "coast", definition: "n. 海岸，海滨"},
    { word: "slide", definition: "v. (使)滑动 n. 滑坡；滑动；幻灯片"},
    { word: "ban", definition: "v. 取缔；禁止 n. 禁止，禁令"},
    { word: "branch", definition: "n. (树)条，分支；分店；(学科)分科，部门；支流"},
    { word: "pack", definition: "v. 打包；塞满 n. 包裹，一群/副"},
    { word: "hence", definition: "adv. 因此；从此，今后"},
    { word: "tool", definition: "n. 工具；方法，手段"},
    { word: "tight", definition: "adj. 紧的；密封的 adv. 紧紧地"},
    { word: "space", definition: "n. 空间；太空"},
    { word: "blow", definition: "v. 吹；吹奏；爆炸 n. 打，打击"},
    { word: "tooth", definition: "n. (pl.teeth)牙齿"},
    { word: "side", definition: "n. 旁边，侧面；一边/侧/方"},
    { word: "sweep", definition: "v. 打，打扫；席卷"},
    { word: "wait", definition: "v./n. 等待"},
    { word: "forth", definition: "adv. 向前；向外"},
    { word: "per", definition: "prep. 每；经，由"},
    { word: "straight", definition: "adj. 直的 adv. 直接；正直"},
    { word: "cake", definition: "n. 蛋糕"},
    { word: "trend", definition: "n. 趋向，趋势"},
    { word: "ware", definition: "n. 器皿，物品"},
    { word: "seal", definition: "v. 密封 n. 印章，海豹"},
    { word: "hang", definition: "v. 悬挂，垂吊；绞死"},
    { word: "wound", definition: "n. 创伤，伤口 v. 伤，伤害"},
    { word: "tube", definition: "n. 管，软管；电子管；地铁"},
    { word: "self", definition: "n. 自己"},
    { word: "ball", definition: "n. 球；舞会"},
    { word: "build", definition: "v. 建造；建设；增大，增强"},
    { word: "pray", definition: "v. 请求；祈祷，祈求"},
    { word: "match", definition: "n. 比赛；配偶；火柴 v. 匹配"},
    { word: "judge", definition: "n. 法官；裁判员 v. 审判；评论"},
    { word: "bounce", definition: "v. 弹起，反弹"},
    { word: "fence", definition: "n. 篱笆；栅栏 v. 用篱笆围住"},
    { word: "print", definition: "n. 印刷 v. 印刷，出版"},
    { word: "strict", definition: "adj. 严格的，严厉的"},
    { word: "sneeze", definition: "v. 打喷嚏 n. 喷嚏"},
    { word: "land", definition: "n. 陆地，土地 v. (使)登陆，降落"},
    { word: "stick", definition: "n. 棍，棒，手杖 v. 刺，戳，扎；粘贴"},
    { word: "pose", definition: "n. 姿势，姿态 v. 造成，提出，摆姿势"},
    { word: "might", definition: "modal.v. 可能，也许 n. 力量，权力"},
    { word: "quote", definition: "v. 引用，援引"},
    { word: "pit", definition: "n. 坑，陷阱；煤矿"},
    { word: "dot", definition: "n. 点，圆点 v. 在……上打点"},
    { word: "hint", definition: "n. 线索 v. 暗示"},
    { word: "bug", definition: "n. 臭虫；小毛病；窃听器 v. 窃听"},
    { word: "rob", definition: "v. 抢劫；(非法)剥夺"},
    { word: "cope", definition: "v. 处理，对付"},
    { word: "toe", definition: "n. 脚趾，足尖"},
    { word: "tongue", definition: "n. 舌；语言"},
    { word: "myth", definition: "n. 神话"},
    { word: "sword", definition: "n. 剑，刀；武力(the sword)"},
    { word: "warn", definition: "v. 警告，告诫"},
    { word: "mask", definition: "n. 面具，面罩；伪装 v. 掩饰，化装"},
    { word: "curb", definition: "v. 制止，抑制 n. 路边"},
    { word: "fake", definition: "n. 假货，赝品 adj. 假的 v. 伪造；伪装"},
    { word: "gloom", definition: "n. 忧郁，阴暗"},
    { word: "deem", definition: "v. 认为，相信"},
    { word: "grace", definition: "n. 优美，文雅"},
    { word: "scar", definition: "n. 疤痕；创伤"},
    { word: "trash", definition: "n. 垃圾；渣滓，败类"},
    { word: "shell", definition: "n. 壳，贝壳；炮弹"},
    { word: "cab", definition: "n. 出租车，驾驶室"},
    { word: "pest", definition: "n. 害虫"},
    { word: "run", definition: "v. 跑；流；经营；运转"},
    { word: "peer", definition: "n. 同辈；同龄人 v. 凝视，隐约出现"},
    { word: "boom", definition: "v. 迅速发展，兴旺"},
    { word: "lure", definition: "v. 引诱，吸引"},
    { word: "pat", definition: "v./n. 轻拍，抚摸"},
    { word: "chill", definition: "n. 寒冷 v. 使寒冷"},
    { word: "fade", definition: "v. 褪色；衰减，消失"},
    { word: "hop", definition: "v./n. 跳"},
    { word: "scope", definition: "n. 范围；机会，余地"},
    { word: "sue", definition: "v. 控告，对……提出诉讼，起诉"},
    { word: "strive", definition: "v. 奋斗，努力"},
    { word: "yell", definition: "v. 大叫；呼喊 n. 叫声；喊声"},
    { word: "bang", definition: "n. 砰砰的声音 v. 砰地关上，猛撞，猛击"},
    { word: "dine", definition: "v. 吃饭，进餐"},
    { word: "chase", definition: "v./n. 追逐，追求"},
    { word: "lag", definition: "v./n. 落后，滞后"},
    { word: "fate", definition: "n. 命运"},
    { word: "thumb", definition: "n. 拇指 v. 迅速翻阅"},
    { word: "sole", definition: "adj. 单独的，唯一的"},
    { word: "trait", definition: "n. 特性，特点，特征"},
    { word: "prey", definition: "n. 猎物，受害者 v. 捕食，掠夺"},
    { word: "pave", definition: "v. 铺砌，铺(路)"},
    { word: "ash", definition: "n. 灰，灰末；(pl.)骨灰"},
    { word: "dump", definition: "v. 倾倒 n. 垃圾场"},
    { word: "rage", definition: "n. 愤怒"},
    { word: "soar", definition: "v. 翱翔；飞涨，激增"},
    { word: "rid", definition: "v. 使摆脱"},
    { word: "glance", definition: "v. 扫视 n. 匆匆看，一瞥"},
    { word: "jet", definition: "n. 喷气式飞机"}
],
window.weekWords.Week6 = [
    { word: "bloom", definition: "n. 花(朵)；开花 v. 开花"},
    { word: "burst", definition: "v. 爆炸；突然发生 n. 突然发生"},
    { word: "blend", definition: "n. 混合(物) v. 混合"},
    { word: "spark", definition: "n. 火花，火星 v. 引起，触发"},
    { word: "dim", definition: "adj. 暗淡的，模糊的"},
    { word: "bold", definition: "adj. 大胆的；；冒失的；黑体的"},
    { word: "peel", definition: "v. 削皮 n. 果皮"},
    { word: "clean", definition: "adj. 清洁的，干净的 v. 使干净"},
    { word: "cup", definition: "n. 杯子；奖杯"},
    { word: "desk", definition: "n. 桌子"},
    { word: "kiss", definition: "n./v. 吻"},
    { word: "May", definition: "n. 五月"},
    { word: "nor", definition: "adv./conj. 也不；也没有"},
    { word: "now", definition: "adv./n. 现在，此刻"},
    { word: "old", definition: "adj. 老的，原来的"},
    { word: "pen", definition: "n. 笔，钢笔"},
    { word: "seem", definition: "v. 看来，好像"},
    { word: "shall", definition: "v. 将要，将会"},
    { word: "since", definition: "prep. 自从 conj. 因为，从……以后 adv. 自从以后；此后"},
    { word: "thank", definition: "v./n. 感谢"},
    { word: "there", definition: "adv. 那里，在那里"},
    { word: "hay", definition: "n. 干草"},
    { word: "fame", definition: "n. 名声；名望"},
    { word: "heel", definition: "n. 脚后跟，踵，鞋跟"},
    { word: "loom", definition: "v. 隐约可见，迫近 n. 织布机"},
    { word: "leap", definition: "v. 跳跃 n. 跳跃，飞跃"},
    { word: "deed", definition: "n. 行为，行动；功绩，事迹"},
    { word: "tempt", definition: "v. 诱惑，引诱"},
    { word: "grave", definition: "adj. 严重的，严肃的 n. 坟墓"},
    { word: "lest", definition: "conj. 惟恐，免得"},
    { word: "scold", definition: "v. 责骂，训斥"},
    { word: "lord", definition: "n. (Lord)上帝；主人，君主，贵族"},
    { word: "browse", definition: "v. 随便翻阅，浏览"},
    { word: "thrive", definition: "v. 兴旺，繁荣"},
    { word: "shrink", definition: "v. 起皱；退缩"},
    { word: "fore", definition: "adv. 在前面 adj. 先前的；在前部的 n.前部"},
    { word: "crude", definition: "adj. 粗制的，天然的；粗鲁的"},
    { word: "mend", definition: "v. 修理；改正，改进"},
    { word: "hoast", definition: "v. 吹嘘；拥有 n. 自夸"},
    { word: "bind", definition: "v. 捆，绑，束缚；使结合"},
    { word: "charm", definition: "n. 吸引力 v. 迷人；施魔法于"},
    { word: "any", definition: "adj. 什么，一些；任何的"},
    { word: "real", definition: "adj. 真的；实际的"},
    { word: "diet", definition: "n. 饮食"},
    { word: "aloud", definition: "adv. 大声地"},
    { word: "ankle", definition: "n. 踝关节"},
    { word: "able", definition: "adj. 能够的"},
    { word: "sofa", definition: "n. 沙发"},
    { word: "tiger", definition: "n. 老虎"},
    { word: "easy", definition: "adj. 容易的"},
    { word: "hero", definition: "n. 英雄；男主角"},
    { word: "ago", definition: "adv. 以前"},
    { word: "cola", definition: "n. 可乐"},
    { word: "winter", definition: "n. 冬天"},
    { word: "china", definition: "n. 瓷器"},
    { word: "study", definition: "v./n. 学习；研究"},
    { word: "money", definition: "n. 钱，款项"},
    { word: "cyber", definition: "adj. 网络的；虚拟的"},
    { word: "giant", definition: "adj. 巨大的 n. 巨人"},
    { word: "labor", definition: "n.(labour) 劳动；劳力 v. 劳动"},
    { word: "tidy", definition: "adj. 整洁的，整齐的 v. 整理，收拾"},
    { word: "double", definition: "adj. 两倍的 v. 加倍"},
    { word: "yellow", definition: "adj. 黄色的 n. 黄色"},
    { word: "curtain", definition: "n. 窗帘，幕布"},
    { word: "cousin", definition: "n. 堂/表兄弟姐妹"},
    { word: "cotton", definition: "n. 棉花"},
    { word: "drity", definition: "adj. 肮脏的"},
    { word: "cafe", definition: "n. 咖啡馆，(小)餐馆"},
    { word: "lion", definition: "n. 狮子"},
    { word: "river", definition: "n. 河；江"},
    { word: "student", definition: "n. 学生"},
    { word: "pupil", definition: "n. 学生"},
    { word: "pencil", definition: "n. 铅笔"},
    { word: "uncle", definition: "n. 叔叔"},
    { word: "eagle", definition: "n. 鹰"},
    { word: "fire", definition: "n. 火"},
    { word: "monkey", definition: "n. 猴子"},
    { word: "unable", definition: "adj. 不能的"},
    { word: "panda", definition: "n. 熊猫"},
    { word: "doctor", definition: "n. 医生，博士"},
    { word: "favor", definition: "n. 好感；喜爱 v. 赞成，支持"},
    { word: "trouble", definition: "n. 麻烦；烦恼；辛苦 v. (使)烦恼"},
    { word: "lady", definition: "n. 女士；夫人"},
    { word: "madam", definition: "n. 女士；夫人"},
    { word: "nothing", definition: "pron./n. 没有什么，一无所有"},
    { word: "tonight", definition: "n. 今晚 adv. 在今晚"},
    { word: "menu", definition: "n. 菜单"},
    { word: "kilo", definition: "n. 千克，公斤"},
    { word: "alter", definition: "v. 改变，变化"},
    { word: "alive", definition: "adj. 活着的；活跃的"},
    { word: "Wi-Fi", definition: "n. 无线网络"},
    { word: "hotel", definition: "n. 酒店；旅馆"},
    { word: "wire", definition: "n. 金属线，电线；电报，电信"},
    { word: "wallet", definition: "n. 钱包；皮夹"},
    { word: "fuel", definition: "n. 燃料 v. 给……加燃料；引起"},
    { word: "eleven", definition: "n. 十一"},
    { word: "saying", definition: "n. 谚语"},
    { word: "quiet", definition: "adj. 安静的 v. 使安静"},
    { word: "either", definition: "adj./adv./pron./det. 两者其中之一 conj. 或者，要么"},
    { word: "window", definition: "n. 窗户"},
    { word: "candy", definition: "n. 糖果"},
    { word: "cherry", definition: "n. 樱桃(树)"},
    { word: "exit", definition: "n. 出口，通道"},
    { word: "data", definition: "n.(datum的复数)资料，数据"},
    { word: "future", definition: "n. 将来，未来；前景 adj. 将来的，未来的"},
    { word: "every", definition: "adj. 每个的；每隔……的；全部的"},
    { word: "away", definition: "adv. 向远处，远离"},
    { word: "agree", definition: "v. 答应，赞同；适合，一致"},
    { word: "open", definition: "v. 打开 adj. 开着的"},
    { word: "hardly", definition: "adv. 几乎不"},
    { word: "table", definition: "n. 表格；桌子"},
    { word: "also", definition: "adv. 也；此外"},
    { word: "become", definition: "v. 变成，成为"},
    { word: "beauty", definition: "v. 变成，成为"},
    { word: "answer", definition: "n./v. 答案，回答"},
    { word: "water", definition: "n. 水 v. 流泪，浇灌"},
    { word: "animal", definition: "n. 动物"},
    { word: "another", definition: "pron./adj. 另一个(的)"},
    { word: "bottle", definition: "n. 瓶子"},
    { word: "many", definition: "adj. 许多的 pron. 许多人或物"},
    { word: "hospital", definition: "n. 医院"},
    { word: "evil", definition: "adj. 邪恶的，罪恶的 n. 邪恶，罪恶"},
    { word: "poem", definition: "n. 诗"},
    { word: "lesson", definition: "n. 教训；经验；课程"},
    { word: "legend", definition: "n. 传奇，传说"},
    { word: "freshman", definition: "n. 大一新生"},
    { word: "marry", definition: "v. 结婚，嫁，娶"},
    { word: "sour", definition: "adj. 酸的"},
    { word: "flour", definition: "n. 面粉"},
    { word: "discuss", definition: "v. 讨论，商议"},
    { word: "duty", definition: "n. 义务，责任；税"},
    { word: "elsewhere", definition: "adv./pron. 在别处"},
    { word: "almost", definition: "adv. 几乎，差不多"},
    { word: "person", definition: "n. 人"},
    { word: "pizza", definition: "n. 披萨"},
    { word: "T-shirt", definition: "n. T恤衫"},
    { word: "turkey", definition: "n. 火鸡"},
    { word: "dolphin", definition: "n. 海豚"},
    { word: "farther", definition: "adv. 更远地 adj. 更远的"},
    { word: "tomato", definition: "n. 西红柿"},
    { word: "potato", definition: "n. 马铃薯，土豆"},
    { word: "onion", definition: "n. 洋葱"},
    { word: "nearby", definition: "adj./adv. 在附近；不远"},
    { word: "silly", definition: "adj. 愚蠢的"},
    { word: "orange", definition: "n. 橙子 adj. 橙色的"},
    { word: "melon", definition: "n. 甜瓜；瓜"},
    { word: "watermelon", definition: "n. 西瓜"},
    { word: "chilli", definition: "n. 辣椒"},
    { word: "pepper", definition: "n. 胡椒粉；甜椒"},
    { word: "lemon", definition: "n. 柠檬"},
    { word: "mango", definition: "n. 芒果"},
    { word: "curry", definition: "n. 咖喱"},
    { word: "chocolate", definition: "n. 巧克力"},
    { word: "listen", definition: "v. 听"},
    { word: "piano", definition: "n. 钢琴"},
    { word: "music", definition: "n. 音乐；乐曲"},
    { word: "inside", definition: "prep./adv. 在(或向)……内 adj. 内部的"},
    { word: "outside", definition: "n. 外部 adj. 外部的；在外面的 prep./adv. 在……外面"},
    { word: "outdoor", definition: "adj. 户外的；室外的"},
    { word: "taxi", definition: "n. 出租汽车 v. (指飞机)滑行"}
],
window.weekWords.Week7 = [
    { word: "science", definition: "n. 科学；学科"},
    { word: "museum", definition: "n. 博物馆"},
    { word: "essey", definition: "n. 文章，短文"},
    { word: "value", definition: "n. 价格；价值 v. 估价；重视"},
    { word: "second", definition: "adj. 第二；次等的 adv. 第二，其次 n. 秒 v. 赞成，支持"},
    { word: "washroom", definition: "n. 洗手间"},
    { word: "meeting", definition: "n. 会议；会面"},
    { word: "woman", definition: "n. 女人，女性"},
    { word: "butter", definition: "n. 黄油"},
    { word: "season", definition: "n. 季，季节，时节"},
    { word: "ocean", definition: "n. 海洋"},
    { word: "hour", definition: "n. 小时"},
    { word: "morning", definition: "n./adj. 早晨；上午"},
    { word: "evening", definition: "n./adj. 傍晚，晚上"},
    { word: "cattle", definition: "n. 牛"},
    { word: "sister", definition: "n. 姐妹"},
    { word: "father", definition: "n. 父亲"},
    { word: "middle", definition: "adj. 中间的 n. 中间；中部"},
    { word: "midnight", definition: "n./adj. 午夜，子夜"},
    { word: "forbid", definition: "v. 禁止"},
    { word: "rubber", definition: "n. 橡胶"},
    { word: "sunshine", definition: "n. 阳光"},
    { word: "today", definition: "n./adv. 今天；当今"},
    { word: "sugar", definition: "n. 糖"},
    { word: "party", definition: "n. 聚会；派对；政党"},
    { word: "funny", definition: "adj. 有趣的，滑稽的"},
    { word: "often", definition: "adv. 经常；往往"},
    { word: "never", definition: "adv. 从不；从未"},
    { word: "merry", definition: "adj. 愉快的"},
    { word: "happy", definition: "adj. 快乐的，高兴的"},
    { word: "unhappy", definition: "adj. 不快乐的；不满意的"},
    { word: "carrot", definition: "n. 胡萝卜"},
    { word: "limit", definition: "n. 界限，范围 v. 限制，限定"},
    { word: "cargo", definition: "n. 船货，货物"},
    { word: "even", definition: "adv. 甚至(更) adj. 均匀的；平的；偶数的"},
    { word: "enter", definition: "v. 进入；加入；开始参加"},
    { word: "upon", definition: "prep. 在……上[=on]"},
    { word: "under", definition: "prep./adv. 在……之下；下面 adj. 下面的"},
    { word: "before", definition: "prep./conj. 在……以前，在……前面 adv. 以前"},
    { word: "after", definition: "prep./conj. 在……以后；在……后面 adv. 以后"},
    { word: "behind", definition: "prep./adv. 在……后面"},
    { word: "until", definition: "conj./prep. 直到……为止，在……以前"},
    { word: "during", definition: "prep. 在……期间"},
    { word: "within", definition: "prep. 在……里面，在……以内 adv. 在内"},
    { word: "without", definition: "prep. 无，没有"},
    { word: "across", definition: "prep. 横过，越过 adv. 横过，穿过"},
    { word: "beyond", definition: "prep. 在(或向)……在那边，远于；超出"},
    { word: "again", definition: "adv. 再一次"},
    { word: "against", definition: "prep. 反对；违反；紧靠着；对比"},
    { word: "upper", definition: "adj. 上面的；上部的，较高的"},
    { word: "above", definition: "adj. 上述的 adv. 在上面 prep. 高于；超过"},
    { word: "between", definition: "prep. 在……之间"},
    { word: "over", definition: "adv. 在上方；遍及地 prep. 在上方 adj. 结束的"},
    { word: "beside", definition: "prep. 在……旁边"},
    { word: "besides", definition: "adv. 此外 prep. 除……之外"},
    { word: "however", definition: "adv. 然而 conj. 无论如何，无论怎样"},
    { word: "unless", definition: "conj. 除非"},
    { word: "library", definition: "n. 图书馆；文库"},
    { word: "ready", definition: "adj. 准备好的"},
    { word: "bowling", definition: "n. 保龄球"},
    { word: "whether", definition: "conj. 是否"},
    { word: "weather", definition: "n. 天气"},
    { word: "asleep", definition: "adj. 睡觉的，睡着的"},
    { word: "always", definition: "adv. 总是，一直，永远"},
    { word: "network", definition: "n. (互联)网络"},
    { word: "mankind", definition: "n. 人类"},
    { word: "robot", definition: "n. 机器人"},
    { word: "topic", definition: "n. 话题，主题，题目"},
    { word: "afraid", definition: "adj. 害怕的，恐惧的"},
    { word: "honest", definition: "adj. 诚实的，正直的"},
    { word: "elder", definition: "adj. 年长的，资格老的 n. 长辈"},
    { word: "kitchen", definition: "n. 厨房"},
    { word: "advise", definition: "v. 建议"},
    { word: "advice", definition: "n. 建议，意见"},
    { word: "carbon", definition: "n. 碳"},
    { word: "carpet", definition: "n. 地毯"},
    { word: "focus", definition: "n. 焦点，中心 v. 使聚焦"},
    { word: "copy", definition: "n. 抄本；(一)本 v. 抄写；抄袭"},
    { word: "biscuit", definition: "n. 饼干"},
    { word: "career", definition: "n. 事业；生涯，职业"},
    { word: "notice", definition: "n./v. 通知；注意"},
    { word: "popular", definition: "adj. 受喜爱的，流行的"},
    { word: "offer", definition: "v. 提供，提议 n. 出价，提议"},
    { word: "develop", definition: "v. 发展，开发，研制；养成"},
    { word: "apart", definition: "adv. 分离，隔开 adj. 分离的"},
    { word: "energy", definition: "n. 活力，精力；能力"},
    { word: "borrow", definition: "v. 借"},
    { word: "level", definition: "n. 水平，等级 v. 使平等；使平整"},
    { word: "error", definition: "n. 错误，过失"},
    { word: "already", definition: "adv. 已经"},
    { word: "reason", definition: "n. 原因，理性 v. 推理"},
    { word: "unkonwn", definition: "adj. 未知的"},
    { word: "danger", definition: "n. 危险；威胁"},
    { word: "boxing", definition: "n. 拳击"},
    { word: "auther", definition: "n. 作者，作家；创始人"},
    { word: "degree", definition: "n. 程度；度数；学位；等级"},
    { word: "paper", definition: "n. 纸；报纸；试卷；论文"},
    { word: "hurry", definition: "v. 匆忙，催促 n. 急(匆)忙"},
    { word: "corner", definition: "n. 角，街角"},
    { word: "around", definition: "prep./adv. 围绕，周围"},
    { word: "explain", definition: "v. 解释，说明"},
    { word: "refuse", definition: "v. 拒绝 n. 废物，垃圾"},
    { word: "repair", definition: "n./v. 修理，修补"},
    { word: "report", definition: "n./v. 报告，汇报"},
    { word: "argue", definition: "v. 辩论，争论；主张，认为"},
    { word: "anger", definition: "n. 愤怒，气愤"},
    { word: "gather", definition: "v. 聚焦，聚拢"},
    { word: "sudden", definition: "adj. 突然的"},
    { word: "leisure", definition: "n. 空闲，闲暇"},
    { word: "usual", definition: "adj. 通常的，平常的"},
    { word: "normal", definition: "adj. 正常的；一般的"},
    { word: "title", definition: "n. 标题；头衔，称号 v. 加标题"},
    { word: "zero", definition: "n. 零，零度 num. 零"},
    { word: "expert", definition: "n. 专家，能手 adj. 熟练的，有经验的"},
    { word: "appear", definition: "v. 出现；看上去"},
    { word: "obey", definition: "v. 服从，顺从"},
    { word: "decide", definition: "v. 决定，下决心"},
    { word: "together", definition: "adv. 共同，一起"},
    { word: "human", definition: "adj. 人的，人类的 n. 人"},
    { word: "being", definition: "n. 生物，生命，存在"},
    { word: "letter", definition: "n. 字母，文字；信"},
    { word: "actor", definition: "n. 演员，男演员；行动者"},
    { word: "actress", definition: "n. 女演员"},
    { word: "belong", definition: "v. 属于"},
    { word: "tennis", definition: "n. 网球"},
    { word: "exist", definition: "v. 存在；生存"},
    { word: "airline", definition: "n. 航空公司；航线"},
    { word: "airport", definition: "n. 机场"},
    { word: "begin", definition: "v. 开始，着手"},
    { word: "humor", definition: "n. 幽默"},
    { word: "hunger", definition: "n. 饥饿 v. 渴望"},
    { word: "college", definition: "n. 学院，高等专科学校，大学"},
    { word: "company", definition: "n. 公司；陪伴"},
    { word: "create", definition: "v. 创造，创作；引起，建立"},
    { word: "forget", definition: "v. 忘记，遗忘"},
    { word: "insect", definition: "n. 昆虫"},
    { word: "army", definition: "n. 军队"},
    { word: "nowhere", definition: "adv. 无处，哪里都不"},
    { word: "police", definition: "n. 警察"},
    { word: "market", definition: "n. 市场 v. 出售，推销"},
    { word: "neither", definition: "adv. 也不"},
    { word: "shampoo", definition: "n. 洗发水 v. 洗发"},
    { word: "maybe", definition: "adv. 大概，或许"},
    { word: "Internet", definition: "n. (国际)互联网；因特网"},
    { word: "idea", definition: "n. 想法；主意"},
    { word: "movie", definition: "n. 电影；影片"},
    { word: "lazy", definition: "adj. 懒惰的"},
    { word: "metre", definition: "n. (meter)米；公尺"},
    { word: "cancer", definition: "n. 癌；肿瘤"},
    { word: "traffic", definition: "n. 交通；运输；通信量"},
    { word: "design", definition: "v./n. 设计；构思"},
    { word: "button", definition: "纽扣，按钮. "},
    { word: "computer", definition: "n. 电脑"},
    { word: "lawyer", definition: "n. 律师"},
    { word: "missing", definition: "adj. 丢失的；缺少的；失踪的"},
    { word: "mistake", definition: "n. 错误 v. 误会；误解；看错"},
    { word: "jacket", definition: "n. 夹克"},
    { word: "salad", definition: "n. 沙拉"},
    { word: "mirror", definition: "n. 镜子 v. 反射；反映"},
    { word: "handbag", definition: "n. 手提包"}
],
window.weekWords.Week8 = [
    { word: "", definition: ""}
],
window.weekWords.Week9 = [
    { word: "", definition: ""}
],
window.weekWords.Week10 = [
    { word: "", definition: ""}
],
window.weekWords.Week11 = [
    { word: "", definition: ""}
],
window.weekWords.Week12 = [
    { word: "", definition: ""}
],
window.weekWords.Week13 = [
    { word: "", definition: ""}
],
window.weekWords.Week14 = [
    { word: "", definition: ""}
],
window.weekWords.Week15 = [
    { word: "", definition: ""}
]